### ISSUE TITLE
Rogue Class - Cooperate with Calamity Mod's new Rogue Class

### ISSUE THREAD

**Issue by xBeston** [SaerusTierialis/tModLoader_ExperienceAndClasses#108]
Please replace the x with your response in all relevant fields.

**Describe the feature that you would like**
I would like a new/updated Rogue Class, this is based off the new Rogue Class from Calamity mod, where Throwing Damage has been modified to Rogue Damage. Basically, it's either a new Rogue Class or a updated Ninja Class with Rogue Damage instead of Throwing Damage.

**Describe any alternatives that you have considered**
It is also possible to implement Ninja to improve BOTH Rogue Damage and Throwing Damage, as Rogue Damage was originally derived from Throwing Damage.

**Additional context**
The stats improvements on the class can be slightly modified, or remained the same to make the new Rogue Class viable, as compared to the other classes and weapons.

**Comment by Shadaris** [comment]
Would have to be careful about the implementation of both. Currently, Calamity devs have addressed this (partially) to work with Thorium mod. The only issue is that Thorium's thrower techniques require the application of throwing damage.

From the page:
Rogue damage is internally throwing damage, because of this, the Rogue and Throwing classes are semi-compatible with each other:
Accessories and armor belonging to the Throwing class that boosts throwing damage will also boost rogue weapons.
Rogue accessories and armor will not boost throwing damage.
Rogue stealth will not boost throwing damage.

**Comment by SaerusTierialis** [comment]
The revised power scaling system can scale any type of damage on any class. This include custom mod damage types.
